name: daily_planner
description: Daily task planner app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  shamsi_date: ^1.0.2
  fl_chart: ^0.66.0

flutter:
  uses-material-design: true
